let mapleader =","
set encoding=utf-8
set nocompatible

filetype on
filetype plugin on
filetype indent on
syntax on

set number relativenumber
set clipboard+=unnamedplus
set title

set shiftwidth=4
set tabstop=4
set expandtab

set nobackup
set nowrap
set incsearch
set nohlsearch
set ignorecase
set smartcase
set showmode

set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
