#!/bin/sh
feh --bg-fill --no-fehbg ~/Pictures/wallpapers/bg.jpg &
picom --backend glx --vsync --unredir-if-possible -f -b &
bar &
gentoo-pipewire-launcher &
exec dbus-launch --sh-syntax --exit-with-session dwm >/dev/null 2>&1
